spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: abu0418
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法
logging:
  level:
    com.youku1327.mybatis.mapper: debug #日志级别